"""initial migration

Revision ID: 85908a1b47cc
Revises: 
Create Date: 2021-09-19 20:24:27.737637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85908a1b47cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_post_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'pitchs', ['pitch_id'], ['id'])
    op.drop_column('upvotes', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_post_id_fkey', 'upvotes', 'pitchs', ['post_id'], ['id'])
    op.drop_column('upvotes', 'pitch_id')
    # ### end Alembic commands ###
